# Site settings
title: Diehl Silers
email: diehlstx@gmail.com
description: Diehl's musings
url: "https://diehlms.github.io"
github_username: diehlms

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md